### ISSUE TITLE
 ContextMenus is not defined

### ISSUE THREAD

**Issue by bigdown** [arnaucode/class2context#1]
Uncaught ReferenceError: ContextMenus is not defined

**Comment by arnaucube** [comment]
yes, sorry, i forget to explain it in the readme.md file
you can define an empty function, like:

``` js
function ContextMenus(){
//nothing inside
};
```

It is designed to put inside the call to the contextmenus creator function, for example:

``` js
function ContextMenus(){
    class2context('class1',"title",[["option1", "function1()"], ["option 2","function2()"]]);
    class2context('class4',"title",[["option1", "function3()"], ["option 2","function4()"]]);
};
```

**That's because** when dealing with a constantly changing DOM html, it needs to re-assign the context menu to the dom elements, and this is done inside this function.
If your html hasn't on the go changes of DOM, you don't need to re-assign the context menus to the dom elements, and can just put the ContextMenus() function empty.
I hope this helps
